### ISSUE TITLE
Not working with non-English(?) Reddit client

### ISSUE THREAD

**Issue by p0358** [lint/TFDidThatSay#3]
As I see in the code, it does check for `[deleted]` body. The issue with this approach is that this body is localized in the Reddit app, which causes the tweak to not trigger on deleted messages in these situations:
![obraz](https://user-images.githubusercontent.com/5182588/79076028-1045d600-7cf7-11ea-8a71-28d6e447d1fb.png)
But as visible, the solution should be dead-simple here, thankfully – it should be enough to switch to checking author name for `[deleted]`, as that doesn't happen to be localized currently. (I'm... really not sure how this thing works, since everything else in my app is in English apparently, only deleted message body seems to be localized...)

**Comment by lint** [comment]
You're right, there's a pretty simple quick fix if I just check the author. I think the reason I only checked the body was because if someone deletes their account, their username is "[deleted]" but their comment text is still visible. I'll look into using Reddit's localizations for "future proofing" and a better solution.

**Comment by lint** [comment]
1.3.3 changed from checking comment/post body to the author to fix this.
